name: Deploy artifacts to Maven Central

on:
  workflow_call:
    secrets:
      centralUsername:
        required: true
      centralPassword:
        required: true
      gpgPrivateKey:
        required: true
      gpgPassphrase:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{secrets.gpgPrivateKey}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy to Maven Central
        run: mvn deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{secrets.centralUsername}}
          MAVEN_CENTRAL_TOKEN: ${{secrets.centralPassword}}
          MAVEN_GPG_PASSPHRASE: ${{secrets.gpgPassphrase}}
